# Generated by Django 4.0 on 2021-12-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=models.CharField(max_length=9999),
        ),
    ]
