# Generated by Django 4.0 on 2021-12-18 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0003_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='categorias',
            field=models.ManyToManyField(to='posteos.Categoria'),
        ),
        migrations.AlterModelTable(
            name='categoria',
            table=None,
        ),
    ]
