# Generated by Django 4.0 on 2021-12-19 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posteos', '0006_remove_categoria_imagen_posteo_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteo',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
