# Generated by Django 4.0 on 2021-12-19 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posteos', '0007_posteo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posteo',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
